version: '1.0'
name: sinor

secrets:
  main_db-password:
    file: mysql/password.txt
  keycloak_db-password:
    file: keycloak/password.txt

volumes:
  cache-redis_db-data: { }
  cache-mysql_db-data: { }
  main-mysql_db-data: { }

networks:
  front-tier:
    external: true
  back-cache-tier:
    external: true
  back-main-tier:
    external: true

services:
  reverse_proxy:
    image: nginx:latest
    ports: # https://docs.docker.com/compose/compose-file/05-services/#long-syntax-3
      - "80:80"
    depends_on:
      cache_server:
        condition: service_started
      main_server:
        condition: service_started
      auth_server:
        condition: service_started
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf

  cache_server:
    hostname: cacheHost
    build: ./cache
    ports:
      - "8000:8000"
    restart: no
    depends_on:
      cache_redis_db:
        condition: service_healthy
      cache_mysql_db:
        condition: service_healthy
    environment:
      - TZ=Asia/Seoul

  cache_redis_db:
    hostname: redisHost
    image: redis:latest
    expose:
      - 6379
    restart: no
    healthcheck: # https://stackoverflow.com/questions/67904609/how-do-you-perform-a-healthcheck-in-the-redis-docker-image
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 3
    volumes:
      - cache-redis_db-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ] # 커스텀 설정 파일 사용


  cache_mysql_db:
    hostname: mysqlHost
    image: mysql:8
    expose:
      - 3306
      - 33060
    restart: no
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysqlHost", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/main_db-password
      - REDIS_HOST=redisHost
      - REDIS_PORT=6379
    secrets:
      - main_db-password
    volumes:
      - cache-mysql_db-data:/var/lib/mysql

  main_server:
    hostname: mainHost
    build: ./main
    ports:
      - "8080:8080"
    restart: no
    depends_on:
      main_db:
        condition: service_healthy

  main_db:
    hostname: mysqlHost_main
    image: mysql:8
    expose:
      - 3306
      - 33060
    restart: no
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysqlHost_main", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_DATABASE=coupang
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/main_db-password
    secrets:
      - main_db-password
    volumes:
      - main-mysql_db-data:/var/lib/mysql

  auth_server:
    hostname: authHost
    build: ./auth
    ports:
      - "9000:9000"
    restart: no
    depends_on:
      cache_redis_db:
        condition: service_healthy
      cache_mysql_db:
        condition: service_healthy




